### ISSUE TITLE
Error: Unauthorized: access to the requested resource is not authorized

### ISSUE THREAD

**Issue by Eggwise** [Syncano/syncano-platform#51]
Hi when trying to run the syncano platform using docker i get the following error:

`Service 'web' failed to build: Unauthorized: access to the requested resource is not authorized`

See screenshot

![image](https://user-images.githubusercontent.com/20506046/65690156-bfc69e00-e06e-11e9-8211-036dff281d51.png)

How can i run the platform locally?

**Comment by maciejkorsan** [comment]
@23doors do you have any idea?

**Comment by Eggwise** [comment]
I think i am getting this error because when composing the following url cannot be accessed https://quay.io/syncano/syncano-platform

See:
https://github.com/Syncano/syncano-platform/blob/devel/docker-compose.yml

Line 46

**Comment by 23doors** [comment]
Try building images first. `docker-compose build`

**Comment by Eggwise** [comment]
@23doors Same error. quay.io/syncano/syncano-platform is protected

**Comment by 23doors** [comment]
It is but you should be able to create your own image for this from `Dockerfile`
try running first:
`docker build  . -t quay.io/syncano/syncano-platform`

**Comment by Eggwise** [comment]
@23doors Thanks.

Had to run  `docker build . -t quay.io/syncano/codebox`aswell, to get it to work.

Now it runs and i can do some further diging in how it all works. Thanks :)
